set nocompatible              " set improved, required.
filetype off                  " required

""""""""""""""""""""""""""""""PLUGINS"""""""""""""""""""""""""""""""""""

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'sudo.vim'
Plugin 'kchmck/vim-coffee-script'
Plugin 'kien/ctrlp.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'
Plugin 'scrooloose/syntastic'
Plugin 'mtscout6/syntastic-local-eslint.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'groovy.vim'
Plugin 'airblade/vim-gitgutter'
Plugin 'bling/vim-airline'
Plugin 'embear/vim-localvimrc'
" Plugin 'Valloric/YouCompleteMe'
" Plugin 'SirVer/ultisnips'
" Plugin 'honza/vim-snippets'
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'octol/vim-cpp-enhanced-highlight'

" Colour themes
Plugin 'Lokaltog/vim-distinguished'
Plugin 'chriskempson/base16-vim'


" For base16-vim?

call vundle#end()             " required
"filetype plugin indent on     " required

" vim-jsx configuration
let g:jsx_ext_required = 0

" NERD tree configuration
" NERDTress File highlighting
function! NERDTreeHighlightFile(extension, fg, bg, guifg, guibg)
 exec 'autocmd FileType nerdtree highlight ' . a:extension .' ctermbg='. a:bg .' ctermfg='. a:fg .' guibg='. a:guibg .' guifg='. a:guifg
 exec 'autocmd FileType nerdtree syn match ' . a:extension .' #^\s\+.*'. a:extension .'$#'
endfunction

au VimEnter * call NERDTreeHighlightFile('md', 'blue', 'none', '#3366FF', '#151515')
au VimEnter * call NERDTreeHighlightFile('json', 'yellow', 'none', 'yellow', '#151515')
au VimEnter * call NERDTreeHighlightFile('html', 'cyan', 'none', 'cyan', '#151515')
au VimEnter * call NERDTreeHighlightFile('styl', 'cyan', 'none', 'cyan', '#151515')
au VimEnter * call NERDTreeHighlightFile('css', 'cyan', 'none', 'cyan', '#151515')
au VimEnter * call NERDTreeHighlightFile('coffee', 'red', 'none', 'red', '#151515')
au VimEnter * call NERDTreeHighlightFile('js', 'yellow', 'none', 'yellow', '#151515')
au VimEnter * call NERDTreeHighlightFile('o', 'grey', 'none', 'grey', '#151515')
au VimEnter * call NERDTreeHighlightFile('cpp', 'yellow', 'none', 'yellow', '#151515')
au VimEnter * call NERDTreeHighlightFile('h', 'cyan', 'none', 'cyan', '#151515')

let NERDTreeIgnore = [ '\.swp' ]

" Syntasic settings
" Recommened settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
" let g:syntastic_aggregate_errors=1 " Something I had?

" Note: For this to work eslint must be installed locally to project
let g:syntastic_javascript_checkers = [ 'eslint' ]
" Point syntastic checker at locally installed `eslint` if it exists.

fun! s:SetSyntasticEslintExec()
  let b:syntastic_javascript_eslint_exec = findfile('node_modules/.bin/eslint', '.;')
  " echo b:syntastic_javascript_eslint_exec
endfunction
autocmd FileType javascript exec s:SetSyntasticEslintExec()

" Airline settings
" Show buffer 'tabs' and use vertical separator.
"let g:airline#extensions#tabline#enabled=1
"let g:airline#extensions#tabline#left_sep = ' '
"let g:airline#extensions#tabline#left_alt_sep = '|'

" Ctrlp settings
let g:ctrlp_map=''
set wildignore+=*/tmp/*,*/node_modules/*,*/dist/*,*/lib/*,*/coverage/*,*.so,*.swp,*.zip
set wildignore+=*/app/components/*

" Fugitive
" Review staged hunks
command Greview :Git! diff --staged

" Ultisnips
let g:UltiSnipsDirectories=['~/.vim/bundle/vim-snippets/UltiSnips']

" vim-localvimrc
let g:localvimrc_persistent=2

""""""""""""""""""""""""""""""SETTINGS"""""""""""""""""""""""""""""""""

set t_Co=256

" Try and fix weird colour in tmux
set t_ut=

set ttimeoutlen=50
set laststatus=2
let g:airline_powerline_fonts=1

" Show matches as typing search regex.
set incsearch

" Enable completion in the command line
set wildmenu
set wildmode=longest:full,full

" Hide buffers when they are abandoned.
set hidden

" Lines to the cursor when scrolling via j/k
set so=7

" Do not show matching braces.
set noshowmatch

" Use magic with search regexs.
set magic

" Disable error bells.
set noerrorbells
set novisualbell
set t_vb=

" Use ack for grepping
set grepprg=ack

" Fancy wrapping?
set wrap
set linebreak
set breakindent
set showbreak=..

""""""""""""""""""""""""""""EDITOR SETTINGS""""""""""""""""""""""""""""

syntax enable

set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set autoindent

set number
set cursorline

" Maybe use base16 doodads?
if filereadable(expand("~/.vimrc_background"))
    let base16colorspace=256
    source ~/.vimrc_background
endif
" colorscheme Tomorrow-Night-Eighties

set encoding=utf8

" Highlight characters outside the 80col border
"highlight rightMargin ctermbg=grey guibg=grey ctermfg=black guifg=black
"match rightMargin /.\%>104v/

""""""""""""""""""""""""""""KEY BINDINGS"""""""""""""""""""""""""""""""

let mapleader="\\"

" Leader mappings
noremap <silent> <Leader><Tab> :NERDTreeToggle <CR>
noremap <silent> <Leader>f :CtrlP<CR>
noremap <silent> <Leader>t :TagbarToggle<CR>
noremap <silent> <Leader>q :xall<CR>
noremap <silent> <Leader>en :cnext<CR>
noremap <silent> <Leader>ep :cprev<CR>


nnoremap <leader>gr :Greview<cr>

" Easier buffer switching.
nnoremap <F5> :buffers<CR>:buffer<Space>

" Snippet settings
let g:UltiSnipsExpandTrigger="<c-e>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

""""""""""""""""""""""""""""AUTO COMMANDS""""""""""""""""""""""""""""""

" Close vim if nerdtree is the only thing open.
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

" Make sure make files use tab characters
autocmd Filetype make setlocal noexpandtab
autocmd Filetype make setlocal softtabstop=0

" Fix up some file types
autocmd BufNewFile,BufRead *.md set filetype=markdown
autocmd BufNewFile,BufRead *.sum set filetype=sum
autocmd BufNewFile,BufRead *.gradle set filetype=groovy

autocmd InsertLeave * :GitGutterAll

""""""""""""""""""""""""""""SPELLING""""""""""""""""""""""""""""""""""
noremap <leader>ss :setlocal spell! spelllang=en_au<cr>

noremap <leader>sn ]s
noremap <leader>sp [s
noremap <leader>sa zg
noremap <leader>s? z=
