# If you come from bash you might have to change your $PATH.
export PATH="/usr/local/bin/:$PATH"

export ZSH="$HOME/.oh-my-zsh"

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# OMZ themes only control your prompt. I've got my own prompt customisation
# ZSH_THEME="murilasso"
# ZSH_THEME="jonathan"

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"
# HYPHEN_INSENSITIVE="true"

zstyle ':omz:update' mode reminder  # just remind me to update when it's time
zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"


# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

HIST_STAMPS="yyyy-mm-dd"

plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration
# export ZSH_CUSTOM=$HOME/.dotfiles/shell/zsh/

# export MANPATH="/usr/local/man:$MANPATH"

configRoot="$HOME/.dotfiles/shell"
source "$configRoot/zsh/prompt.sh"
source "$configRoot/shared/aliases.sh"
source "$configRoot/shared/autoconfed.sh"
source "$configRoot/shared/base16-shell.sh"
source "$configRoot/shared/completion.sh"
source "$configRoot/shared/env.sh"

[[ -f $HOME/.zshrc.local ]] && source "$HOME/.zshrc.local"
