#!/usr/bin/env bash


# If not running interactively, don't do anything
[[ "$-" != *i* ]] && return

bashDotfileRoot="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
echo "source dir $bashDotfileRoot"

# umask 027

# Load configs
. "$HOME/.dotfiles/bash/conf/shell-options.sh"
. "$HOME/.dotfiles/bash/conf/env.sh"
. "$HOME/.dotfiles/bash/conf/autoconfed.sh"

. "$HOME/.dotfiles/bash/conf/base16-shell.sh"

. "$HOME/.dotfiles/bash/conf/aliases.sh"
. "$HOME/.dotfiles/bash/conf/completion.sh"
. "$HOME/.dotfiles/bash/conf/prompt.sh"

. "$HOME/.dotfiles/bash/conf/base16-shell.sh"


. "$HOME/.dotfiles/bash/scripts/nvm.conf.sh"

. "$HOME/.dotfiles/bash/scripts/running.sh"
